name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    # Step 3: Build the Docker image and apply migrations
    - name: Build Docker image with migrations
      run: |
        docker build -t harithchin1673/patient-service:latest .
        docker run --rm harithchin1673/patient-service:latest python manage.py migrate

    # Step 4: Push the Docker image to DockerHub
    - name: Push Docker image
      run: docker push harithchin1673/patient-service:latest
