name: Build and Deploy Docker Image with MySQL

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Wait for AWS RDS MySQL (or your MySQL DB) to be ready
    - name: Wait for MySQL
      env:
        DB_HOST: ${{ secrets.MYSQL_HOST }}
        DB_PORT: 3306
        DB_USER: ${{ secrets.MYSQL_USER }}
        DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: |
        until mysqladmin ping -h $DB_HOST -u $DB_USER -p$DB_PASSWORD; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    # Step 5: Apply database migrations
    - name: Apply migrations
      env:
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: 3306
      run: python manage.py migrate

    # Step 6: Run integration tests (optional)
    - name: Run tests
      env:
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: 3306
      run: python manage.py test

    # Step 7: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 8: Build Docker image
    - name: Build Docker image
      run: docker build -t harithchin1673/patient-service:latest .

    # Step 9: Push Docker image
    - name: Push Docker image
      run: docker push harithchin1673/patient-service:latest

    # Step 9: Run Docker container
    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 \
          --name patient-service \
          -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
          -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
          -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
          harithchin1673/patient-service:latest