name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t harithchin1673/patient-service:latest .

    # Step 4: Run the Docker container (for testing)
    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 \
          --name patient-service \
          harithchin1673/patient-service:latest

    # Step 5: Wait for the container to be ready
    - name: Wait for the service to start
      run: sleep 10

    # Step 6: Test the application
    - name: Run Integration Tests
      run: docker exec patient-service python manage.py test patients.tests.test_integration

    # Step 7: Push the Docker image to DockerHub
    - name: Push Docker image
      run: docker push harithchin1673/patient-service:latest

    # Step 8: Debugging - List containers (Optional)
    - name: Debug - List Docker containers
      run: docker ps -a
